# Generated by Django 2.2.4 on 2019-08-28 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_appoint_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoint',
            name='address',
            field=models.CharField(max_length=50),
        ),
    ]
